defaults:
  - data: samson
  - model: hsae
  - trainer: default_trainer
  - optimizer: adam

load_ckpt: null

checkpoint:
  dirpath: "ckpts"
  save_last: True
  save_top_k: 1
  period: 1
  mode: "min"
  filename: "{epoch}"

seed: 42
stdout: ${trainer.logging_level}
id: "${model.id}_${data.id}"

hydra:
  run:
    dir: "./data/runs/${now:%Y-%m-%d_%H-%M-%S}/${id}"
  sweep:
    dir: "./data/runs/${now:%Y-%m-%d_%H-%M-%S}/"
    subdir: "${id}"
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(name)s][%(levelname)s] - %(message)s'
      detailed:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: ${stdout}
        stream: ext://sys.stdout
      file:
        class : logging.handlers.RotatingFileHandler
        formatter: detailed
        level: DEBUG
        filename: debug.log
    root:
      handlers: [console, file]

    disable_existing_loggers: false

