mode: "supervised"
seed: 0
SNR: Null
runs: 1
display: False
torch: False
wandb: False

defaults:
  - dataset : SDC
  - normalizer: PixelwiseL2Norm
  - setter: DS
  - initializer: VCA
  - model: DS
  - aligner: munkres
  - noise: AWGN
  - criterion: MAE
  - cluster: OAR
  - launcher: default
  - _self_


stdout: INFO

hydra:
  run:
    # dir: "./data/runs/${now:%Y-%m-%d_%H-%M-%S}/${id}"
    dir: "./data/runs/${now:%Y-%m-%d_%H-%M-%S}"
  sweep:
    dir: "./data/runs/${now:%Y-%m-%d_%H-%M-%S}/"
    # subdir: "${id}"
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(name)s][%(levelname)s] - %(message)s'
      detailed:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: ${stdout}
        stream: ext://sys.stdout
      file:
        class : logging.handlers.RotatingFileHandler
        formatter: detailed
        level: DEBUG
        filename: debug.log
    root:
      handlers: [console, file]

    disable_existing_loggers: false

