_target_: hsi_unmixing.models.blind.AlternatingEDA
eta0A: 1.0
eta0B: 0.001
KA: 100
KB: 100
A_init: "softmax"
B_init: "pSVD"
schemeA: "flat"
schemeB: "flat"
nb_alternating: 100
device: Null
use_projection: False
entropic_regularization: False
denoise: False
epsilon: 1e-2
