class_name: HSAE
id: "${model.class_name}"
params:
  H: ${data.params.H}
  W: ${data.params.W}
  n_endmembers: ${data.params.n_endmembers}
  n_bands: ${data.params.n_bands}
  dropout: 0.2
  threshold: 1.0
  deep: true
  base:
    loss: "sad"
    save_figs_dir: "figures"
    optimizer:
      class_name: ${optimizer.class_name}
      params:
        lr: ${optimizer.params.lr}
