class_name: SparseCoding_pw
id: "${model.class_name}"
params:
  n_endmembers: ${data.params.n_endmembers}
  n_bands: ${data.params.n_bands}
  unrollings: 5
  # lambd_init: 0.1
  nu_init: 1.0
  gamma_init: 0.1
  use_C: False
  use_W: False
