class_name: SparseCoding_pw
id: "${model.class_name}"
params:
  # H: ${data.params.H}
  # W: ${data.params.W}
  n_endmembers: ${data.params.n_endmembers}
  n_bands: ${data.params.n_bands}
  unrollings: 5
  # dropout: 0.2
  lambd_init: 0.1
  use_C: False
  use_W: False
  # base:
  #   loss: "sad"
  #   save_figs_dir: "figures"
  #   optimizer:
  #     class_name: ${optimizer.class_name}
  #     params:
  #       lr: ${optimizer.params.lr}
