engine: "OAR"
directive: "#OAR"
cleanup: "source gpu_setVisibleDevices.sh"
cmd: "oarsub -S"
frontal_node: "edgar"
shell:
  bin_path: "/usr/bin/zsh"
  config_path: "~/.zshrc"
launchers: ["default", "besteffort"]
conda_env: ${oc.env:CONDA_DEFAULT_ENV}
